### ISSUE TITLE
Belarusian language

### ISSUE THREAD

**Issue by antikruk** [And42/TranslatorApk#1]
Добавьте белорусский язык, пожалуйста 
[translatorapkby.txt](https://github.com/And42/TranslatorApk/files/1172243/translatorapkby.txt)
Во флагах вместо белорусского бельгийский флаг

**Comment by And42** [comment]
Спасибо, добавлю и поправлю

**Comment by mosnster** [comment]
When the editor translates, the symbol is changed, causing the software to display abnormally

**Comment by mosnster** [comment]
example:
 (%d) -> (٪ d)

**Comment by And42** [comment]
@mosnster, that's because online translators can't understand this shouldn't be translated. Unfortunately, I can't change this logic as I can't collect all the different phrase modifications (%d - ٪ d, %2d - 2 % d and so on) and as they can change over time. 
The only solution right now is to check them all manually.
If you have a suggestion that may work let me know

**Comment by mosnster** [comment]
@And42 
you look https://github.com/jinguangyue/AndroidStringsOneTabTranslation

**Comment by mosnster** [comment]
@And42 https://github.com/onlynight/Translator

**Comment by And42** [comment]
I've looked through them and found that noone uses special logic to avoid modifications (%d - ٪ d), the reason is that Bing and Google translators do not make such mistakes so they don't need to correct anything. Unfortunately, I can't use these services as Google is paid (i don't want to pay for everyone) and Bing is free but it's pretty hard to make it work (you need to visit marketplace, sign up, subscribe to service etc). That's why I use only Baidu (where you don't need to do anything) and Yandex (where you can recieve api key is a few clicks)

**Comment by mosnster** [comment]
@And42 Thank you's work

**Comment by mosnster** [comment]
@And42 hi,bro.
i have google translate api,Use this software how to call?

**Comment by mosnster** [comment]
@And42  My Friend, I have a suggestion: you can directly create the dictionary by the value of all the translation, is equivalent to generate a different language dictionary, and then generate the corresponding language according to the dictionary, if it can be done automatically, then it is so good, so Do not have every language to translate those unnecessary options.

**Comment by mosnster** [comment]
@And42 This is to change the logic of the program, first use the default values in the string with the local language (that is, the way to generate a dictionary), and then directly translated into multiple languages (you can choose the language you need.) This is simple and efficient to complete Localized needs.

**Comment by And42** [comment]
@antikruk, создал проект для перевода: https://osnlpjg.oneskyapp.com/collaboration/project?id=297707. Предложенные строки добавлю в следующую версию. С флагами несколько сложнее будет

**Comment by antikruk** [comment]
Так а в чем загвоздка с флагами? Картинку поменяйте просто. Be - код белорусского языка. В Бельгии французский и голландский. А если по странам флаги сортируете, то Беларуси код BY а не Be

**Comment by And42** [comment]
@antikruk Проблема в том, что на данный момент все флаги подобраны по коду страны, а по этому коду Be относится к Бельгии. Необходимо перевести все флаги под код языка, что и является загвоздкой. Кроме того, необходимо найти новые флаги языков, потому что на текущих проставлены надписи в всоответствии с кодами стран, а не языков. А так как весь этот проект делается исключительно на энтузиазме, то основной проблемой является выделение времени на него, а не исправление ошибок

**Comment by antikruk** [comment]
Ну так я ж про это и говорю. Если нет времени на перевод на классификацию по коду языка, картинку подменить просто, ибо Бельгийского языка нет и флаг Бельгии не нужен. Файлы какого расширения используете?

**Comment by And42** [comment]
Если имеется ввиду расширение флагов, то .png, в Files/Resources/Flags лежат

**Comment by antikruk** [comment]
![values-be](https://user-images.githubusercontent.com/6292989/36691995-ebacf99e-1b47-11e8-95a1-c81bd67c7431.png)
